name: Create Dockerfile

on:
  workflow_dispatch:
    push:
      branches:
        - main
      path:
        - backend/*

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Send echo command
        working-directory: /
        run: echo "Hello"